# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Push generated package to GitHub registry
      run: |   
        dotnet nuget push src/*/bin/Release/Rox.*.nupkg -k ${{ secrets.NugetKey }} -s https://www.nuget.org/ --skip-duplicate
        
#    - name: dotnet publish
#      run: dotnet publish --configuration -c Release --no-restore -o app  

    - name: Copy BaC
      run: |
        cp -rf samples/Barbecue/bin/Release/net6.0/publish ./app
    - name: Copy Dockerfile
      run: cp Dockerfile ./app
    - name: Login To Docker
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
          tags: |
            crazor6/bulls_and_cows:latest
          context: ./app
          push: true
    - name: Docker Images Lst
      run: docker images
